# NumPy

* Numerical Python kısaltmasıdır.
* Bilimsel hesaplamalar için kullanılır.
* Arrayler / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
* Listelere benzerdir. Farkı; verimli veri saklama ve vektorel operasyonlardır. 

![title](numpy.png)

# Neden NumPy ? 

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]

In [3]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [6]:
a*b

array([ 2,  6, 12, 20])

Görüldüğü üzere daha az çaba ile daha büyük işler yapabilme olanağı sağlar.
NumPy yer tutma maliyetlerini en aza indirmektedir. (En az 4 kat daha az)

# NumPy Array'i Oluşturmak

NumPy Array'i listeler, sözlükler gibi bir veri tipidir.

In [7]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5])

In [9]:
type(a)

numpy.ndarray

In [10]:
np.array([3.14, 4, 2, 13])

array([ 3.14,  4.  ,  2.  , 13.  ])

Tüm sayıları ondalık bir sayı olacak şekilde çevirdi. NumPy içerisinde sadece tek tip veri tutmaktadır. **dtype** argümanı ile tanımlama esnasında istediğimiz veri tipini belirleyebiliriz.

In [11]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

### Sıfırdan Array Olusturma

In [12]:
np.zeros(10, dtype = "int") #Sıfırlardan oluşan

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones([3,5], dtype = "int") #Birlerden oluşan

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5), 3, dtype = "int") #Bizim belirlediğimiz sayıdan oluşan

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [15]:
np.arange(0,31, 3) #Doğrusal bir diziden oluşan

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.linspace(0,1,10) # 0 ile 1 arasında 10 tane sayıdan oluşan

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.random.normal(10, 4, (3,4)) #Ortalaması 10, standart sapması 4 normal dağılımlı 3'e 4'lük matris

array([[13.47493371,  8.24346438, 11.78032025, 21.16666614],
       [13.37713506, 11.69048681, 10.58846331, 10.37524858],
       [14.07221515, 15.09328145, 14.8422987 , 10.64671112]])

In [18]:
np.random.randint(0,10, (3,3)) # integer degerlerden oluşan

array([[8, 3, 3],
       [4, 5, 2],
       [0, 5, 8]])

### NumPy Array Özellikleri

* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [19]:
import numpy as np

In [20]:
np.random.randint(10, size = 10)

array([4, 9, 8, 7, 4, 2, 3, 3, 3, 2])

In [21]:
a = np.random.randint(10, size = 10)

In [22]:
a.ndim #tek boyutlu

1

In [23]:
a.shape #tek boyutlu oldugu için bir boyut bilgisi verilecek

(10,)

In [24]:
a.size

10

In [25]:
a.dtype

dtype('int64')

In [26]:
b = np.random.randint(10, size = (3,5))
b

array([[3, 8, 9, 2, 5],
       [9, 5, 3, 4, 8],
       [0, 6, 3, 4, 4]])

In [27]:
b.ndim #iki boyutlu

2

In [28]:
b.shape #bir boyutta 3, diğer boyutta 5 eleman var

(3, 5)

In [29]:
b.size

15

In [30]:
b.dtype

dtype('int64')

### Yeniden Şekillendirme (reshaping)

In [31]:
import numpy as np

In [32]:
np.arange(1,10) #amacım bu array üzerinden 3'e 3'lük bir array oluşturmak

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a = np.arange(1,10) #tek boyutlu array'i matrise çevirmek istiyoruz ama tek boyut bilgilerini taşısın..
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
b = a.reshape((1,9))
b.ndim

2

### Array Birleştirme (Concatenation)

In [37]:
import numpy as np

In [38]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [39]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [40]:
z = np.array([7,8,9])

In [41]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
#iki boyut üzerine oluşturmak istersek;

In [43]:
a = np.array([[1,2,3], 
             [4,5,6]]) #manuel olarak iki boyutlu array oluşturduk.

In [44]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
np.concatenate([a,a], axis = 1) # axis argümanı ile sutün bazında birleştirme yaptık.
#axis argümanının ön tanımlı değeri 0'dır ve satır bazında birleştirme sağlar.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Array Ayırma (Splitting)

In [46]:
import numpy as np

In [47]:
x = np.array([1,2,3,99,99,3,2,1]) # bu array'i 3 parçaya ayırmak istersek;

In [48]:
np.split(x, [3,5]) # index mantıgı ile ("e kadar")

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

* Bölmüş olduğumuz her bir array'i yakalayıp kullanmak istersek ne yapacağız?

In [49]:
a,b,c = np.split(x, [3,5])

In [50]:
a

array([1, 2, 3])

In [51]:
b

array([99, 99])

In [52]:
c

array([3, 2, 1])

In [53]:
#iki boyutlu ayırma (dikey olarak yan yana koyma islemi)

In [54]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.vsplit(m, [2]) #2. indexe kadar böl

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [56]:
ust, alt = np.vsplit(m, [2])
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
#iki boyutlu ayırma (yatay olarak yan yana koyma islemi)

In [58]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [60]:
sol, sag = np.hsplit(m, [2])
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

## Array Sıralama (Sorting)

In [61]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [62]:
np.sort(v)

array([1, 2, 3, 4, 5])

* sort() metodu numpy içerisinden çağrıldığında veri setinin orjinal yapısını bozmaz.
* fakat v.sort() olarak kullanılırsa veri setinin yapısında degisiklik meydana gelir.

In [63]:
#iki boyutlu array üzerinde sıralama

In [64]:
m = np.random.normal(20,5, (3,3))
m

array([[20.68308872, 26.74125488, 17.30746381],
       [24.46631707, 18.16896322, 23.75874016],
       [18.621968  , 20.94721217, 21.35128191]])

* amacım bu iki boyutlu array'in satırlarını sıralamak olsun;

In [65]:
np.sort(m, axis = 1)

array([[17.30746381, 20.68308872, 26.74125488],
       [18.16896322, 23.75874016, 24.46631707],
       [18.621968  , 20.94721217, 21.35128191]])

In [66]:
np.sort(m, axis = 0) #stunları sıraladık

array([[18.621968  , 18.16896322, 17.30746381],
       [20.68308872, 20.94721217, 21.35128191],
       [24.46631707, 26.74125488, 23.75874016]])

### Index ile Elamanlara Erişmek

In [67]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([6, 7, 5, 6, 3, 8, 8, 4, 6, 2])

In [68]:
a[0]

6

In [69]:
a[-1]

2

In [70]:
a[0] = 100
a

array([100,   7,   5,   6,   3,   8,   8,   4,   6,   2])

In [71]:
#iki boyutlu array üzerinden index ile elamana erişmek

In [72]:
m = np.random.randint(10, size = (3,5))
m

array([[0, 0, 6, 7, 3],
       [1, 6, 6, 0, 6],
       [7, 2, 6, 6, 1]])

In [73]:
m[0,0]

0

In [74]:
m[1,1]

6

In [75]:
m[1,4]

6

In [76]:
m[1,4] = 99
m

array([[ 0,  0,  6,  7,  3],
       [ 1,  6,  6,  0, 99],
       [ 7,  2,  6,  6,  1]])

* ! farklı tipte bir değişkeni array içerisine eklemek istersek, örneğin integer veri tipinde olan bir array'a float bir değer eklemek istersek, integer olarak ekleyecektir. 

In [77]:
m[1,4] = 80.2
m

array([[ 0,  0,  6,  7,  3],
       [ 1,  6,  6,  0, 80],
       [ 7,  2,  6,  6,  1]])

### Array Alt Kümesine Erişmek (Slicing)

In [78]:
import numpy as np
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [79]:
a[0:3] #0'dan 3'e kadar (index mantıgı)

array([20, 21, 22])

In [80]:
a[:3]

array([20, 21, 22])

In [81]:
a[3:] #3'ten sonra kadar

array([23, 24, 25, 26, 27, 28, 29])

In [82]:
a[1::2] #1.indexten ikişer ikişer atlayarak sona kadar git

array([21, 23, 25, 27, 29])

In [83]:
a[0::2]

array([20, 22, 24, 26, 28])

In [84]:
a[0::3] # 3'er 3'er

array([20, 23, 26, 29])

In [85]:
#iki boyutlu slice islemleri

In [86]:
m = np.random.randint(10, size = (5,5))
m

array([[0, 2, 1, 5, 8],
       [3, 3, 9, 2, 8],
       [8, 8, 4, 1, 0],
       [2, 2, 8, 6, 3],
       [6, 0, 1, 1, 9]])

In [87]:
m[:,0] #tüm satırları sec fakat 0. sütun

array([0, 3, 8, 2, 6])

In [88]:
m[:,4] #tüm satırları sec fakat 4. sütunu al

array([8, 8, 0, 3, 9])

In [89]:
m[0,:] #0.satır ve tüm sütunlar

array([0, 2, 1, 5, 8])

In [90]:
m[0]

array([0, 2, 1, 5, 8])

In [91]:
m[1,:]

array([3, 3, 9, 2, 8])

* hem satırlara hem sütunlara birlikte erişmek istersek;

In [92]:
m[0:2, 0:3] #0'dan 2'ye kadar satırları, 0'dan 3'e kadar sütunları al

array([[0, 2, 1],
       [3, 3, 9]])

In [93]:
m[::,:2] #tüm satırları ve ilk 2 sütunu al

array([[0, 2],
       [3, 3],
       [8, 8],
       [2, 2],
       [6, 0]])

In [94]:
m[1:3,0:2] #1. ve 3. index satırını ve 0'dan 2'ye kadar olan sütunları al

array([[3, 3],
       [8, 8]])

In [95]:
m

array([[0, 2, 1, 5, 8],
       [3, 3, 9, 2, 8],
       [8, 8, 4, 1, 0],
       [2, 2, 8, 6, 3],
       [6, 0, 1, 1, 9]])

In [96]:
m[:2,2] #tüm satırları al fakat 2. sütunu (index) sec.

array([1, 9])

### Alt Küme Üzerinde İşlem Yapmak

In [97]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[1, 6, 9, 2, 3],
       [0, 6, 5, 4, 3],
       [5, 9, 3, 5, 4],
       [6, 0, 7, 5, 4],
       [2, 4, 0, 5, 9]])

In [98]:
alt_a = a[0:3, 0:2]
alt_a

array([[1, 6],
       [0, 6],
       [5, 9]])

In [99]:
alt_a[0,0] = 9999
alt_a[1,1] = 888
alt_a

array([[9999,    6],
       [   0,  888],
       [   5,    9]])

In [100]:
a

array([[9999,    6,    9,    2,    3],
       [   0,  888,    5,    4,    3],
       [   5,    9,    3,    5,    4],
       [   6,    0,    7,    5,    4],
       [   2,    4,    0,    5,    9]])

* ! alt kümede yapılan değişiklik ana arrayi bozdu. Bunu önlemek için;

In [101]:
import numpy as np
m = np.random.randint(10, size = (5,5))
m

array([[7, 5, 2, 8, 4],
       [5, 3, 1, 7, 2],
       [7, 0, 1, 2, 5],
       [8, 3, 1, 7, 3],
       [3, 3, 0, 3, 1]])

In [102]:
alt_b = m[0:3, 0:2].copy()
alt_b
#copy() metodu seçmiş olduğumuz alt kümeyi ana kümeden bağımsızlastırır.

array([[7, 5],
       [5, 3],
       [7, 0]])

In [103]:
alt_b[0,0] = 9999
alt_b

array([[9999,    5],
       [   5,    3],
       [   7,    0]])

In [104]:
m

array([[7, 5, 2, 8, 4],
       [5, 3, 1, 7, 2],
       [7, 0, 1, 2, 5],
       [8, 3, 1, 7, 3],
       [3, 3, 0, 3, 1]])

* ! görüleceği gibi oluşturmuş olduğumuz ana array üzerinde hiçbir değişiklik meydana gelmemiştir. Fakat seçmiş oldugumuz alt kümede istediğimiz değişikliği yapabilir konuma ulaştık.

### Fancy Index ile Elemanlara Erişmek

* Fancy, bize daha ileri düzeyde eleman seçme imkanı sağlamaktadır

In [105]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [106]:
v[1]

3

In [107]:
v[3]

9

In [108]:
v[5]

15

In [109]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [110]:
#yüzlerce index içerisinden istediğimiz degerleri tek tek nasıl cekebiliriz?

In [111]:
al_getir = [1,3,5]

In [112]:
v[al_getir]

array([ 3,  9, 15])

* ! Elimizdeki yüzlerce döngü ve fonksiyon çıktısını bir array içerisinden çağırmak istiyorsak bu şekilde basitçe çağırabiliyoruz. Buna fancy işlemi denir. (index mantığı ile)

In [113]:
#iki boyutta fancy

In [114]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [116]:
m[satir, sutun]

array([1, 5])

In [117]:
#basit index ile fancy index

In [118]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [119]:
m[0,[1,2]]

array([1, 2])

In [120]:
#slice ile fancy

In [121]:
m[0:, [1,2]] #tüm satırları ve 1. ve 2. sutunları seç. (e kadar yok, fancy ile calısmıs oldu)

array([[1, 2],
       [4, 5],
       [7, 8]])

### Koşullu Eleman İşlemleri

In [122]:
import numpy as np
v = np.array([1,2,3,4,5])

In [123]:
v > 5 #v array icerisindeki elemanların 5'ten büyük olup olmadıgını sorgular

array([False, False, False, False, False])

In [124]:
v < 3

array([ True,  True, False, False, False])

* peki belirtilen şartı sağlayanları nasıl yakalarız?

In [125]:
v[v < 3] #sorgulama sonucunda true olan degerleri yakalamış olduk

array([1, 2])

In [126]:
v[v >= 3]

array([3, 4, 5])

In [127]:
v[v == 3]

array([3])

In [128]:
v[v != 3]

array([1, 2, 4, 5])

### Matematiksel İşlemler

In [129]:
import numpy as np
v = np.array([1,2,3,4,5])

In [130]:
v - 1

array([0, 1, 2, 3, 4])

In [131]:
v * 5

array([ 5, 10, 15, 20, 25])

In [132]:
v*5+1

array([ 6, 11, 16, 21, 26])

In [133]:
#ufunc

In [134]:
np.subtract(v,1) #cıkarma islemi

array([0, 1, 2, 3, 4])

In [135]:
np.add(v,1) #toplama islemi

array([2, 3, 4, 5, 6])

In [136]:
np.multiply(v,4) #carpma islemi

array([ 4,  8, 12, 16, 20])

In [137]:
np.divide(v,3) #bolme islemi

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [138]:
np.power(v,3) #kuvvet alma

array([  1,   8,  27,  64, 125])

In [139]:
np.mod(v,2) #mod fonksiyonu (2'ye bölümünden kalanlar)

array([1, 0, 1, 0, 1])

In [140]:
 np.absolute(np.array([-2])) #mutlak deger alma

array([2])

In [141]:
np.sin(360)

0.9589157234143065

In [142]:
np.cos(180)

-0.5984600690578581

In [143]:
v = np.array([1,2,3])
np.log(v)  #logaritmik islemler

array([0.        , 0.69314718, 1.09861229])

np.log2(v)

In [144]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

* numpy ile kullanabileceğimiz islemlere ?np kodu ile erişebiliriz.

### İstatistiksel Hesaplamalar

In [145]:
np.mean(v, axis = 0)

2.0

In [146]:
v.sum()

6

In [147]:
v.min()

1

### NumPy ile İki Bilinmeyenli Denklem Çözümü

5*x0 + x1 = 12

x0 + 3*x1 = 10

In [148]:
a = np.array([[5,1], [1,3]]) #degisken katsayılını aldık
b = np.array([12,10]) #esitligin diger tarafındaki degerler

In [149]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])